[package]
name = "hig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.2"
git2 = "0.18.0"
serde = { version = "1.0.188", features = ["derive"] }
toml = "0.7.8"
