name: Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Set up Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Build project
              run: cargo build --release

            - name: Upload artifact
              uses: actions/upload-artifact@v4.6.0
              with:
                  name: ${{ matrix.os }}
                  path: target/release/

    release:
        needs: build
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Download artifacts
              uses: actions/download-artifact@v4.1.8
              with:
                  path: ./artifacts

            - name: Create a Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: ${{ github.ref }}
                  prerelease: false
                  files: ./artifacts/*
