name: Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Set up Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Build project
              run: cargo build --release

            - name: Upload artifact
              uses: actions/upload-artifact@v4.6.0
              with:
                  name: ${{ matrix.os }}
                  path: target/release/

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4.1.8
              with:
                  path: ./artifacts
            - name: Create a Release
              uses: elgohr/Github-Release-Action@v5
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  title: hig
                  workdir: ./artifacts
